version: "3"

services:
  app:
    image: cleaningrecord_api:latest
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ../../cleaningrecord:/cleaningrecord
      - ./app/static:/static
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"  
    env_file:
      - .env
    environment:
      - DB_HOST=192.168.0.229
      - DB_NAME=app
      - DB_USER=clean_records
      - DB_PASS=Mallory@486
      - DEBUG=1
    
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'clean_records'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Mallory@486'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Mallory@486'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./app/scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
  # Names our volume
  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/static
    ports:
      - "80:80"
    depends_on:
      - app  

volumes:
  my-db:
  static:

networks:
    default: 
       external:
            name: cleaningrecordapi_default