# Generated by Django 3.2.9 on 2021-11-26 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberDriver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_first_name', models.CharField(max_length=500)),
                ('driver_last_name', models.CharField(blank=True, max_length=500)),
                ('driver_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UberRegisteredCar',
            fields=[
                ('uber_car_id', models.AutoField(primary_key=True, serialize=False)),
                ('uber_car_rego', models.CharField(max_length=15)),
                ('uber_car_vin', models.CharField(max_length=100)),
                ('uber_car_insurance_provider', models.CharField(max_length=150)),
                ('uber_car_insurance_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UberTempCleaningRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_trip', models.TextField()),
                ('date_and_time_of_clean', models.TextField()),
                ('driver_name', models.TextField()),
                ('driver_certificate_number', models.TextField()),
                ('passenger_high_touch_surfaces', models.TextField()),
                ('driver_high_touch_surfaces', models.TextField()),
                ('driver_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UberDriverTripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_phone_number', models.CharField(max_length=15)),
                ('driver_email', models.CharField(max_length=50)),
                ('driver_trip_id', models.CharField(max_length=50)),
                ('driver_trip_type', models.CharField(max_length=15)),
                ('driver_trip_base_fare', models.CharField(max_length=5)),
                ('driver_trip_cancellation_fare', models.CharField(blank=True, max_length=5)),
                ('driver_trip_date_time', models.CharField(max_length=45)),
                ('driver_trip_fare_min_or_supplement', models.CharField(blank=True, max_length=5)),
                ('driver_trip_fare_supplement', models.CharField(blank=True, max_length=5)),
                ('driver_trip_wait_time', models.CharField(blank=True, max_length=5)),
                ('driver_trip_service_fee', models.CharField(blank=True, max_length=5)),
                ('driver_trip_tip', models.CharField(blank=True, max_length=5)),
                ('driver_trip_total', models.CharField(max_length=10)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdriver')),
            ],
        ),
        migrations.CreateModel(
            name='UberDriverCPVVCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_certificate_id', models.CharField(max_length=5)),
                ('driver_cpvv_certicate', models.CharField(max_length=25)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdriver')),
            ],
        ),
        migrations.CreateModel(
            name='UberDriverContactInfo',
            fields=[
                ('driver_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_contact_type', models.CharField(max_length=20)),
                ('driver_contact_value', models.CharField(max_length=1000)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdriver')),
            ],
        ),
        migrations.CreateModel(
            name='UberDriverCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdriver')),
                ('uber_car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberregisteredcar')),
            ],
        ),
        migrations.CreateModel(
            name='UberCleaningRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_trip', models.DateTimeField()),
                ('date_and_time_of_clean', models.DateTimeField()),
                ('passenger_high_touch_surfaces', models.CharField(max_length=5)),
                ('driver_high_touch_surfaces', models.CharField(max_length=5)),
                ('driver_certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdrivercpvvcertificate')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uberdriver')),
            ],
        ),
    ]
