# Generated by Django 3.2.9 on 2021-11-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211127_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Driver_Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_CPVV_Certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_Car_Insurance_Cover',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_Car_Insurance_Provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_Car_Rego',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_Car_VIN',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Driver_License',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Landline_Number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Middle_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_Mobile',
        ),
    ]
