# Generated by Django 3.2.9 on 2021-11-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211127_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='date_and_time_of_clean',
            new_name='Date_and_Time_of_clean',
        ),
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='date_and_time_of_trip',
            new_name='Date_and_time_of_trip',
        ),
    ]
