# Generated by Django 3.2.9 on 2021-11-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211127_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='driver_certificate_number',
            new_name='Driver_certificate_number',
        ),
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='driver_high_touch_surfaces',
            new_name='Driver_hightouch_surfaces_cleaned',
        ),
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='passenger_high_touch_surfaces',
            new_name='Passenger_hightouch_surfaces_cleaned',
        ),
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='driver_name',
            new_name='Driver_name',
        ),
        migrations.RenameField(
            model_name='ubertempcleaningrecords',
            old_name='driver_email',
            new_name='Driver_email',
        ),

    ]
